baseURL = 'https://giagoulas.com/'
languageCode = 'en-us'
title = 'Giagoulas Photography'
copyright = "Â© Alexander Giagoulas 2026"
defaultContentLanguage = "en"
#disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = "120s"

theme = ["gallery","hugo-cloak-email"]

[params]
  defaultTheme = "light"
  description = "Photography portfolio of Alexander Giagoulas"
  title = "Giagoulas Photography"
  [params.author]
    email = "alexander@giagoulas.com"
    name = "Alexander Giagoulas"
  [params.socialIcons]
    instagram = "https://www.instagram.com/giagoulasphoto"
    github = "https://github.com/agiagoulas"
    linkedin = "https://www.linkedin.com/in/alexander-giagoulas/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[services]
  [services.rss]
    limit = 100

[imaging]
  quality = 85
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50

[build]
  noJSConfigInAssets = true